//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InspectionProcess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectionResult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InspectionResult()
        {
            this.Keepings = new HashSet<Keeping>();
        }
    
        public int InspectionResultId { get; set; }
        public int InspectionId { get; set; }
        public int ProductId { get; set; }
        public int Count { get; set; }
        public int NormalNumber { get; set; }
        public int DefectiveNumber { get; set; }
    
        public virtual Inspection Inspection { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Keeping> Keepings { get; set; }
    }
}
