//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InspectionProcess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Keeping
    {
        public int InspectionResultId { get; set; }
        public int WarehouseId { get; set; }
        public System.DateTime KeepingDate { get; set; }
    
        public virtual InspectionResult InspectionResult { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
