//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InspectionProcess.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InspectionProcessEntities : DbContext
    {
        public InspectionProcessEntities()
            : base("name=InspectionProcessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Inspection> Inspections { get; set; }
        public virtual DbSet<InspectionResult> InspectionResults { get; set; }
        public virtual DbSet<Keeping> Keepings { get; set; }
        public virtual DbSet<Merchandise> Merchandises { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<Warehouse> Warehouses { get; set; }
    }
}
